// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"go.demo/ent/member"
	"go.demo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescFirstName is the schema descriptor for firstName field.
	memberDescFirstName := memberFields[1].Descriptor()
	// member.FirstNameValidator is a validator for the "firstName" field. It is called by the builders before save.
	member.FirstNameValidator = memberDescFirstName.Validators[0].(func(string) error)
	// memberDescLastName is the schema descriptor for lastName field.
	memberDescLastName := memberFields[2].Descriptor()
	// member.LastNameValidator is a validator for the "lastName" field. It is called by the builders before save.
	member.LastNameValidator = memberDescLastName.Validators[0].(func(string) error)
	// memberDescCreatedAt is the schema descriptor for createdAt field.
	memberDescCreatedAt := memberFields[3].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the createdAt field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
	// memberDescUpdatedAt is the schema descriptor for updatedAt field.
	memberDescUpdatedAt := memberFields[4].Descriptor()
	// member.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	member.DefaultUpdatedAt = memberDescUpdatedAt.Default.(func() time.Time)
	// memberDescID is the schema descriptor for id field.
	memberDescID := memberFields[0].Descriptor()
	// member.DefaultID holds the default value on creation for the id field.
	member.DefaultID = memberDescID.Default.(func() uuid.UUID)
}
